# Generated by Django 5.2.5 on 2025-08-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usermemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('personality', models.TextField(default='Friendly, helpful, and intelligent.')),
            ],
        ),
    ]
