# Generated by Django 5.2.5 on 2025-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cloned_voice_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='cloned_voice_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
