# Generated by Django 5.2.5 on 2025-08-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cloned_voice_id_user_cloned_voice_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cloned_voice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cloned_voice_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
